manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/cobowers/
  projects:
    - name: zmk-mouse-ftc
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
