manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cobowers
      url-base: https://github.com/cobowers
  projects:
    - name: zmk-mouse-ftc
      remote: cobowers
      revision: main
      import: app/west.yml
  self:
    path: config
