manifest:
  remotes:
    - name: zmkfirmware
      url-base: git@github.com/cobowers/zmk-mouse-ftc
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
